service: employee-attendance-backend

provider:
  name: aws
  runtime: python3.9
  region: ${env:AWS_REGION, 'ap-south-1'}
  stage: dev
  memorySize: 3008
  timeout: 300
  httpApi:
    cors: true
  environment:
    ATTENDANCE_TABLE: ${env:ATTENDANCE_TABLE, 'attendance'}
    EMPLOYEE_TABLE: ${env:EMPLOYEE_TABLE, 'employee'}
    S3_BUCKET: ${env:S3_BUCKET, 'employee-face-data'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:*"
            - "s3:*"
          Resource: "*"

package:
  patterns:
    - "!venv/**"
    - "!.env"
    - "!.git/**"
    - "!.gitignore"
    - "!.next/**"
    - "!node_modules/**"

functions:
  api:
    handler: app.main.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
    strip: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - setuptools
